### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by AnXing233** [saberhaoren/haoren#15]
新建没开始写的md文件时，命名后面能不能加个“未完成”标识，减少频繁点击

个人觉得这网站挺好的，帮到一堆像我这样的电子小白XD 希望网站越做越好

**Comment by saberhaoren** [comment]
hi，@shadow01a 

我们其实原意是打算使用✔或❌的形式来进行标记，但由于本项目名称是链接的文件名称，所以没有成功，我们会考虑使用增加较长文件名称的方式来进行管理。

感谢您的提醒，我们会尽快修改。

祝您生活愉快。
saberhaoren

**Comment by saberhaoren** [comment]
@AnXing233 

您好，目前该内容已解决，我们将关闭这个issue，您可以上网站查询相关的建议落实情况。

祝您生活愉快，
saberhaoren
