### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by shadow01a** [saberhaoren/haoren#16]
”如何安装操作系统“网页图片显示有问题
![image](https://github.com/saberhaoren/haoren/assets/141255649/78b1b309-a4fb-48b6-858d-89c5aba61274)

**Comment by saberhaoren** [comment]
hi，@shadow01a 

这个问题我们上周合并时已经知悉，预计今天晚上能够得到修复~我们每周仅有少数时间有空当管理这方面的内容。

感谢您的提醒，我们会尽快修改。

祝您生活愉快。
saberhaoren
