### ISSUE TITLE
添加B站视频链接

### ISSUE THREAD

**Issue by shadow01a** [saberhaoren/haoren#17]
部分在B站上已经做好的视频，可以在网站对应文档开头处加入视频链接，实现补充。
（有时候直接看视频更方便）

**Comment by saberhaoren** [comment]
hi，@shadow01a 

您好！

真是实用的建议，我们会采纳，并在修改完毕后通知您并关闭这个issue。

祝您生活愉快，
saberhaoren

**Comment by saberhaoren** [comment]
hi，@shadow01a 

您好！

我们已经将做好视频的内容链接添加到对应文档的开头处了，您可以随时登录查看。

祝您生活愉快，
saberhaoren
