### ISSUE TITLE
文件夹放错位置了

### ISSUE THREAD

**Issue by Hysen233** [saberhaoren/haoren#47]
![Screenshot_2024-07-17-22-53-20-373_com microsoft emmx](https://github.com/user-attachments/assets/c56c3659-7ffb-4a96-bfae-c4181b37b155)

**Comment by Hysen233** [comment]
清朝老片这个文件夹是不是应该在content文件夹下面

**Comment by shadow01a** [comment]
这个文件夹好像是个提交错误……

**Comment by shadow01a** [comment]
PR #50 已被合并
