### ISSUE TITLE
“史记-硬盘”的图片问题

### ISSUE THREAD

**Issue by shadow01a** [saberhaoren/haoren#49]
网页“史记-硬盘”上的图片全部缺失。

初步调查，发现该网页指向的原文件的图片引用方式似乎与其它文件不同，但在开发者模式下查看时，文件的图片引用方式与其它文件相同，应该可以排除格式相关的问题。（另外图片在obsidian下是正常的）

查看控制台，发现在关于图片的请求中，均 **报错404** ，且其它有图片的网页并没有出现报错。

综上所述，图片缺失的原因不能确定。

在调查中，我们还发现“史记-硬盘”引用图片的总大小达到了惊人的 **219.56M** ，占了总项目大小的约 **80%** ！

即使图片缺失的问题与其惊人的大小无关，这也势必会导致网页图片加载的缓慢。而经过我的转码和适当的压缩，在不影响图片分辨率并且与原图接近的情况下，这些图片的总大小只有 48.96M。 

当然，这还不是极限。原图的分辨率有4000×3000，还包含了一些不必要的部分，如果继续压缩、裁切，图片总大小可以逼近 30M 。

目前这些图片的压缩已经完成，可以提交PR。

**Comment by ravizhan** [comment]
![image](https://github.com/user-attachments/assets/2b4ed8fb-4b06-4a5c-ae57-585cfa094c9a)
![image](https://github.com/user-attachments/assets/66461da5-f39a-40b4-9033-ca2d02815cdb)
对比一下就知道了，作者引用方式写错了
可以开PR了）

**Comment by shadow01a** [comment]
那我去开个PR，合并后再关闭issues

**Comment by shadow01a** [comment]
由于PR已经合并，我会关闭该issues
