### ISSUE TITLE
关于添加如何给此项目贡献的建议

### ISSUE THREAD

**Issue by johnisaway285** [saberhaoren/haoren#58]
看了一下readme，我觉得如果在readme里添加如何给这个repository贡献（How to Contribute）会不会更清晰呢？

**Comment by shadow01a** [comment]
在 [B站](https://www.bilibili.com/video/BV1bE421A7Lo/) 上有一段教程，或许可以引用一下？

**Comment by johnisaway285** [comment]
可以 :+1:

**Comment by shadow01a** [comment]
既然PR #60 已经合并，那可以关闭issue了
