### ISSUE TITLE
“如何安装office套件”中的图片问题

### ISSUE THREAD

**Issue by shadow01a** [saberhaoren/haoren#63]
调查了一下，发现该文章中下载图片所依赖网站存在大陆无法正常访问的问题，需要修改。
@shenbourne 这可能与您有关

**Comment by shenbourne** [comment]
我引用的图片的源也是在GitHub搭建的图库，所以不会出现此类问题啊。是不是加速器没加速GitHub？有空我会修复的。图片的存放模式似乎有过修改，我先摸索下

**Comment by shadow01a** [comment]
为了模拟一下小白，特意没开加速器。

**Comment by shadow01a** [comment]
既然已经修复，我就关闭议题了
